# Generated by Django 5.0.2 on 2024-02-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_recruiter', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_recruiter.recruiterprofile'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_recruiter.recruiterprofile'),
        ),
    ]
