# Generated by Django 5.0.2 on 2024-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_recruiter', '0006_alter_address_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_pictures'),
        ),
    ]
