# Generated by Django 5.0.2 on 2024-02-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0002_alter_talentprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='introduction',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_talent.talentprofile')),
            ],
        ),
    ]
