# Generated by Django 5.0.2 on 2024-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0004_workexperience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'Work Experience'},
        ),
    ]
