# Generated by Django 5.0.2 on 2024-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0005_alter_education_options_alter_workexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('College', 'College'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctor', 'Doctor'), ('Professor', 'Professor'), ('Certificate', 'Certificate')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
