# Generated by Django 5.0.2 on 2024-03-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0009_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies', models.TextField(max_length=300)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_talent.talentprofile')),
            ],
            options={
                'verbose_name_plural': 'Tech Stack',
            },
        ),
    ]
