# Generated by Django 5.0.2 on 2024-03-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0010_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='talent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_talent.talentprofile'),
        ),
    ]
