# Generated by Django 5.0.2 on 2024-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_talent', '0012_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='talent_pictures'),
        ),
    ]
