# Generated by Django 5.0.2 on 2024-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_type',
            field=models.CharField(choices=[('Talent', 'Talent'), ('Recruiter', 'Recruiter'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
